baseurl = "https://ankibues.github.io"
title = "Ankit Bhandari"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 5

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[frontmatter]
  omit_date = true


[params]
  author = "Ankit Bhandari"
  description = "Quality Assurance Engineer and Compliance Project Manager"
  keywords = "blog,software,science,writer, art"
  info = "Project Management | Software Development | Quality Assurance | Technical and Creative Writing"
  avatarurl = "images/photo.jpeg"
  favicon_32 = "images/bhandlab.png"
  favicon_16 = "images/bhandlab.png"
  footerContent = "I don't know anything, but I do know that everything is interesting if you go into it deeply enough -Richard Feynman"
  dateFormat ="January 2, 2006"
  hideFooter = false
  hideCredits = false
  since = 2023

  rtl = false
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false
  maxSeeAlsoItems = 5
  customCSS = []
  customSCSS = []
  customJS = []

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows raw HTML in Markdown content

# utterances comment
[params.utterances]
  enable = true
  repo = "ankibues/bhandlab.github.io"
  issueTerm = "pathname"
  label= "Comments"
  theme = "github-light"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ankibues/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"  
  weight = 2
  url = "https://twitter.com/ankibues/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/ankit-bhandari-56a45772/"

[[params.social]]
name = "Medium"
icon = "fa fa-medium fa-2x"
weight = 4
url = "https://medium.com/@bhand-ab/"

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 2
            url = "projects/"
            
            [[languages.en.menu.main]]
            name = "Publications"
            weight = 3
            url = "publications/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 4
            url = "contact/"
