baseurl = "http://bhandlab.github.io"
title = "BhandLab"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Ankit Bhandari"
  description = "Quality Assurance Engineer and Compliance Project Manager"
  keywords = "blog,developer,science,writer, art"
  info = "Software Quality Assurance/ Software Compliance and Project Management/ Scientific Computing/ Technical and Creative Writing"
  avatarurl = "images/photo.jpeg"
  favicon_32 = "images/bhandlab.png"
  favicon_16 = "images/bhandlab.png"
  footerContent = "The only comfort in being uncomfortable is that you know you are learning."
  
  dateFormat ="January 2, 2006"
  hideFooter = false
  hideCredits = false
  since = 2021

  rtl = false
  enableTwemoji = true
  colorScheme = "dark"
  hidecolorschemetoggle = false
  maxSeeAlsoItems = 5
  customCSS = []
  customSCSS = []
  customJS = []

# utterances comment
[params.utterances]
  enable = true
  repo = "ankibues/bhandlab.github.io"
  issueTerm = "pathname"
  label= "Comments"
  theme = "github-light"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ankibues/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/ankibues/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/ankit-bhandari-56a45772/"

[[params.social]]
name = "Medium"
icon = "fa fa-medium fa-2x"
weight = 4
url = "https://medium.com/@bhand-ab/"

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 2
            url = "projects/"
            
            [[languages.en.menu.main]]
            name = "Publications"
            weight = 3
            url = "publications/"
            
            [[languages.en.menu.main]]
            name = "Resume/C.V."
            weight = 4
            url = "media/CV.pdf"

            [[languages.en.menu.main]]
            name = "Posts"
            weight = 5
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 6
            url = "contact/"